In [8]:
import numpy as np

In [37]:
shape = int(input())

3


In [38]:
if shape == 4:
    matrix_a = np.array([[10, 6, 2, 0],
                      [5, 1, -2, 4],
                      [3, 5, 1, -1],
                      [0, 6, -2, 2]])
if shape == 3:
    matrix_a = np.array([[1, 2, 1],
                      [2, 1, 1],
                      [1, -1, 2]])

In [39]:
def lu_razl(mat_a):
    n = len(mat_a[0])
    mat_lu = np.empty([n, n])
    for i in range(n):
        for j in range(n):
            if i == 0:
                mat_lu[i][j] = mat_a[i][j]
                if j > i:
                    mat_lu[j][i] = mat_a[j][i] / mat_lu[i][i]
            else:
                if j >= i:
                    vr = 0
                    for k in range(i):
                        vr += mat_lu[i][k] * mat_lu[k][j]
                    mat_lu[i][j] = mat_a[i][j] - vr
                if j >= i+1:
                    vr = 0
                    for k in range(i):
                        vr += mat_lu[j][k] * mat_lu[k][i]
                    mat_lu[j][i] = (mat_a[j][i] - vr) / mat_lu[i][i]
    return mat_lu

In [40]:
lu = lu_razl(matrix_a)

In [41]:
lu

array([[ 1.,  2.,  1.],
       [ 2., -3., -1.],
       [ 1.,  1.,  2.]])

In [42]:
def landu(mat_lu, loru = 'l'):
    n = len(mat_lu[0])
    if loru == 'l':
        for i in range(n):
            for j in range(n):
                if i == j:
                    mat_lu[i][j] = 1
                if j > i:
                    mat_lu[i][j] = 0
        return mat_lu
    if loru == 'u':
        for i in range(n):
            for j in range(n):
                if i > j:
                    mat_lu[i][j] = 0
        return mat_lu

In [43]:
print(f"L = \n{landu(lu.copy(), 'l')}\n U = \n{landu(lu.copy(), 'u')}\n B = L * X - A\n {np.matmul(landu(lu.copy(), 'l'), landu(lu.copy(), 'u')) - matrix_a}" )

L = 
[[1. 0. 0.]
 [2. 1. 0.]
 [1. 1. 1.]]
 U = 
[[ 1.  2.  1.]
 [ 0. -3. -1.]
 [ 0.  0.  2.]]
 B = L * X - A
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
