In [13]:
import numpy as np

In [14]:
matrix_a = np.array([[2, 1, 3],
                    [11, 7, 5],
                    [9, 8, 4]])
b = np.array([1, -6, -5])

In [15]:
def lu_razl(mat_a):
    n = len(mat_a[0])
    mat_lu = np.empty([n, n])
    for i in range(n):
        for j in range(n):
            if i == 0:
                mat_lu[i][j] = mat_a[i][j]
                if j > i:
                    mat_lu[j][i] = mat_a[j][i] / mat_lu[i][i]
            else:
                if j >= i:
                    vr = 0
                    for k in range(i):
                        vr += mat_lu[i][k] * mat_lu[k][j]
                    mat_lu[i][j] = mat_a[i][j] - vr
                if j >= i+1:
                    vr = 0
                    for k in range(i):
                        vr += mat_lu[j][k] * mat_lu[k][i]
                    mat_lu[j][i] = (mat_a[j][i] - vr) / mat_lu[i][i]
    return mat_lu

In [16]:
lu = lu_razl(matrix_a)

In [17]:
def landu(mat_lu, loru = 'l'):
    n = len(mat_lu[0])
    if loru == 'l':
        for i in range(n):
            for j in range(n):
                if i == j:
                    mat_lu[i][j] = 1
                if j > i:
                    mat_lu[i][j] = 0
        return mat_lu
    if loru == 'u':
        for i in range(n):
            for j in range(n):
                if i > j:
                    mat_lu[i][j] = 0
        return mat_lu

In [35]:
landu(lu.copy(), 'u')

array([[  2.        ,   1.        ,   3.        ],
       [  0.        ,   1.5       , -11.5       ],
       [  0.        ,   0.        ,  17.33333333]])

In [59]:
def found_vec_y(mat_l, vec):
    n = len(mat_l[0])
    y = np.zeros(n)
    for i in range(len(mat_l[0])):
        vr = 0
        for j in range(i+1):
            if j < i:
                vr += mat_l[i][j] * y[j]
            if j == i:
                y[i] = (vec[i] - vr) / mat_l[i][j]
    return y

In [60]:
y = found_vec_y(landu(lu.copy(), 'l'), b)

In [61]:
y

array([  1.        , -11.5       ,  17.33333333])

In [64]:
def found_vec_x(mat_u, vec):
    n = len(mat_u[0])
    x = np.zeros(n)
    for i in range(n):
        vr = 0
        for j in range(i+1):
            if (n - j - 1) > (n - i - 1):
                vr += mat_u[n - i - 1][n - j - 1] * x[n - j - 1]
            if (n - j - 1) == (n - i - 1):
                x[n - i - 1] = (vec[n - i - 1] - vr) / mat_u[n - i - 1][n - j - 1]
    return x

In [66]:
x = found_vec_x(landu(lu.copy(), 'u'), y)

In [67]:
x

array([-1.,  0.,  1.])

In [70]:
print(f"TEST\n x = {x}\n A * x = {np.matmul(matrix_a, x)}\n b = {b}")

TEST
 x = [-1.  0.  1.]
 A * x = [ 1. -6. -5.]
 b = [ 1 -6 -5]
